import { expect, test } from 'bun:test'
import { PublicKey, Transaction } from '@solana/web3.js'
import type { ManifestAdapter } from '../packages/adapters/solana/manifest/adapter'
import type { ManifestBrowserWallet } from '../packages/adapters/solana/manifest/browser'
import { TRADE_STEPS } from '../packages/adapters/solana/manifest/steps'
import type { ManifestBinding } from '../packages/adapters/solana/manifest/wire'
import { releaseProfileOrder, submitProfileSale } from '../src/components/portfolio/profileActions'
const owner=new PublicKey(new Uint8Array(32).fill(1)),other=new PublicKey(new Uint8Array(32).fill(2))
const binding={outcome:1} as ManifestBinding
const bid={sequence:'77',side:'BUY' as const},offer={sequence:'77',side:'SELL' as const}
function fixture(seat:{venueAvailableUsdc?:bigint;venueAvailableClaims?:bigint}={}){let sent=0;const requests:unknown[]=[];const steps:string[]=[];const adapter={readBook:async()=>({bids:()=>[{trader:owner,sequenceNumber:77n},{trader:other,sequenceNumber:88n}],asks:()=>[]}),cancel:async(_owner:PublicKey,b:ManifestBinding,ids:bigint[])=>{requests.push({b,ids});return new Transaction()},holdings:async()=>({venueAvailableClaims:5n,venueAvailableUsdc:0n,...seat}),moveTokens:async(_owner:PublicKey,b:ManifestBinding,asset:string,atoms:bigint,direction:string)=>{requests.push({b,asset,atoms,direction});return new Transaction()},order:async(_owner:PublicKey,b:ManifestBinding,input:unknown)=>{requests.push({b,input});return new Transaction()}} as unknown as ManifestAdapter;const wallet={owner,send:async(_tx:Transaction,step?:string)=>{sent++;steps.push(step??'');return 'signature'}} as unknown as ManifestBrowserWallet;return {adapter,wallet,requests,steps,sent:()=>sent}}
test('release cancels exactly the owner’s order and then takes the seat balance to the wallet',async()=>{const f=fixture({venueAvailableUsdc:41_600_000n});expect(await releaseProfileOrder(f.adapter,f.wallet,binding,bid,'fUSDC')).toEqual({cancelled:true,withdrawn:41_600_000n});expect(f.requests).toEqual([{b:binding,ids:[77n]},{b:binding,asset:'USDC',atoms:41_600_000n,direction:'withdraw'}]);expect(f.steps).toEqual([TRADE_STEPS.cancelOrder,TRADE_STEPS.withdrawSeat('fUSDC')])})
test('an order already off the book still withdraws what its cancellation left behind',async()=>{const f=fixture({venueAvailableUsdc:40_000_000n});expect(await releaseProfileOrder(f.adapter,f.wallet,binding,{sequence:'88',side:'BUY'},'fUSDC')).toEqual({cancelled:false,withdrawn:40_000_000n});expect(f.sent()).toBe(1);expect(f.steps).toEqual([TRADE_STEPS.withdrawSeat('fUSDC')])})
test('an empty seat signs the cancellation and nothing else',async()=>{const f=fixture({venueAvailableUsdc:0n});expect(await releaseProfileOrder(f.adapter,f.wallet,binding,bid,'fUSDC')).toEqual({cancelled:true,withdrawn:0n});expect(f.sent()).toBe(1);expect(f.steps).toEqual([TRADE_STEPS.cancelOrder])})
test('a released offer withdraws shares, never collateral',async()=>{const f=fixture({venueAvailableClaims:120_000_000n});expect(await releaseProfileOrder(f.adapter,f.wallet,binding,offer,'fUSDC')).toEqual({cancelled:true,withdrawn:120_000_000n});expect(f.requests[1]).toEqual({b:binding,asset:'claims',atoms:120_000_000n,direction:'withdraw'});expect(f.steps[1]).toBe(TRADE_STEPS.withdrawShares)})
test('reserved/unavailable shares cannot enter a profile sale',async()=>{const f=fixture();await expect(submitProfileSale(f.adapter,f.wallet,binding,{side:'SELL',quantity:6n,priceMicros:500000n,lastValidSlot:0,kind:'IOC',maxFeeAtoms:1n})).rejects.toThrow('Reserved shares');expect(f.sent()).toBe(0)})
test('sale preserves the selected outcome, quantity and partial-fill policy',async()=>{const f=fixture();const input={side:'SELL' as const,quantity:5n,priceMicros:500000n,lastValidSlot:0,kind:'IOC' as const,maxFeeAtoms:1n};expect(await submitProfileSale(f.adapter,f.wallet,binding,input)).toBe('signature');expect(f.requests).toEqual([{b:binding,input}])})
test('wallet rejection and uncertain confirmation propagate without another send',async()=>{const f=fixture({venueAvailableUsdc:40_000_000n});let attempts=0;f.wallet.send=async()=>{attempts++;throw new Error('Check transaction signature before retrying: confirmation unavailable')};await expect(releaseProfileOrder(f.adapter,f.wallet,binding,bid,'fUSDC')).rejects.toThrow('before retrying');expect(attempts).toBe(1)})
