/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentArenaRouteImport } from './routes/agent-arena'
import { Route as BetOrMarketRouteImport } from './routes/bet-or-market'
import { Route as CatwalkRouteImport } from './routes/catwalk'
import { Route as ColacatRouteImport } from './routes/colacat'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as MiawPrixRouteImport } from './routes/miaw-prix'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as Events2IdRouteImport } from './routes/events-2/$id'
import { Route as Events3IdRouteImport } from './routes/events-3/$id'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as ChainNetworkAddressRouteImport } from './routes/$chain/$network/$address'
import { Route as Events2IdPredictionIdRouteImport } from './routes/events-2/$id/$predictionId'
import { Route as Events3IdPredictionIdRouteImport } from './routes/events-3/$id/$predictionId'
import { Route as EventsIdPredictionIdRouteImport } from './routes/events/$id/$predictionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentArenaRoute = AgentArenaRouteImport.update({
  id: '/agent-arena',
  path: '/agent-arena',
  getParentRoute: () => rootRouteImport,
} as any)
const BetOrMarketRoute = BetOrMarketRouteImport.update({
  id: '/bet-or-market',
  path: '/bet-or-market',
  getParentRoute: () => rootRouteImport,
} as any)
const CatwalkRoute = CatwalkRouteImport.update({
  id: '/catwalk',
  path: '/catwalk',
  getParentRoute: () => rootRouteImport,
} as any)
const ColacatRoute = ColacatRouteImport.update({
  id: '/colacat',
  path: '/colacat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const MiawPrixRoute = MiawPrixRouteImport.update({
  id: '/miaw-prix',
  path: '/miaw-prix',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const Events2IdRoute = Events2IdRouteImport.update({
  id: '/events-2/$id',
  path: '/events-2/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Events3IdRoute = Events3IdRouteImport.update({
  id: '/events-3/$id',
  path: '/events-3/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainNetworkAddressRoute = ChainNetworkAddressRouteImport.update({
  id: '/$chain/$network/$address',
  path: '/$chain/$network/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const Events2IdPredictionIdRoute = Events2IdPredictionIdRouteImport.update({
  id: '/$predictionId',
  path: '/$predictionId',
  getParentRoute: () => Events2IdRoute,
} as any)
const Events3IdPredictionIdRoute = Events3IdPredictionIdRouteImport.update({
  id: '/$predictionId',
  path: '/$predictionId',
  getParentRoute: () => Events3IdRoute,
} as any)
const EventsIdPredictionIdRoute = EventsIdPredictionIdRouteImport.update({
  id: '/$predictionId',
  path: '/$predictionId',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-arena': typeof AgentArenaRoute
  '/bet-or-market': typeof BetOrMarketRoute
  '/catwalk': typeof CatwalkRoute
  '/colacat': typeof ColacatRoute
  '/demo': typeof DemoRoute
  '/live': typeof LiveRoute
  '/markets': typeof MarketsRoute
  '/miaw-prix': typeof MiawPrixRoute
  '/profile': typeof ProfileRoute
  '/watch': typeof WatchRoute
  '/events-2/$id': typeof Events2IdRouteWithChildren
  '/events-3/$id': typeof Events3IdRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/$chain/$network/$address': typeof ChainNetworkAddressRoute
  '/events-2/$id/$predictionId': typeof Events2IdPredictionIdRoute
  '/events-3/$id/$predictionId': typeof Events3IdPredictionIdRoute
  '/events/$id/$predictionId': typeof EventsIdPredictionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-arena': typeof AgentArenaRoute
  '/bet-or-market': typeof BetOrMarketRoute
  '/catwalk': typeof CatwalkRoute
  '/colacat': typeof ColacatRoute
  '/demo': typeof DemoRoute
  '/live': typeof LiveRoute
  '/markets': typeof MarketsRoute
  '/miaw-prix': typeof MiawPrixRoute
  '/profile': typeof ProfileRoute
  '/watch': typeof WatchRoute
  '/events-2/$id': typeof Events2IdRouteWithChildren
  '/events-3/$id': typeof Events3IdRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/$chain/$network/$address': typeof ChainNetworkAddressRoute
  '/events-2/$id/$predictionId': typeof Events2IdPredictionIdRoute
  '/events-3/$id/$predictionId': typeof Events3IdPredictionIdRoute
  '/events/$id/$predictionId': typeof EventsIdPredictionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-arena': typeof AgentArenaRoute
  '/bet-or-market': typeof BetOrMarketRoute
  '/catwalk': typeof CatwalkRoute
  '/colacat': typeof ColacatRoute
  '/demo': typeof DemoRoute
  '/live': typeof LiveRoute
  '/markets': typeof MarketsRoute
  '/miaw-prix': typeof MiawPrixRoute
  '/profile': typeof ProfileRoute
  '/watch': typeof WatchRoute
  '/events-2/$id': typeof Events2IdRouteWithChildren
  '/events-3/$id': typeof Events3IdRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/$chain/$network/$address': typeof ChainNetworkAddressRoute
  '/events-2/$id/$predictionId': typeof Events2IdPredictionIdRoute
  '/events-3/$id/$predictionId': typeof Events3IdPredictionIdRoute
  '/events/$id/$predictionId': typeof EventsIdPredictionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-arena'
    | '/bet-or-market'
    | '/catwalk'
    | '/colacat'
    | '/demo'
    | '/live'
    | '/markets'
    | '/miaw-prix'
    | '/profile'
    | '/watch'
    | '/events-2/$id'
    | '/events-3/$id'
    | '/events/$id'
    | '/$chain/$network/$address'
    | '/events-2/$id/$predictionId'
    | '/events-3/$id/$predictionId'
    | '/events/$id/$predictionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-arena'
    | '/bet-or-market'
    | '/catwalk'
    | '/colacat'
    | '/demo'
    | '/live'
    | '/markets'
    | '/miaw-prix'
    | '/profile'
    | '/watch'
    | '/events-2/$id'
    | '/events-3/$id'
    | '/events/$id'
    | '/$chain/$network/$address'
    | '/events-2/$id/$predictionId'
    | '/events-3/$id/$predictionId'
    | '/events/$id/$predictionId'
  id:
    | '__root__'
    | '/'
    | '/agent-arena'
    | '/bet-or-market'
    | '/catwalk'
    | '/colacat'
    | '/demo'
    | '/live'
    | '/markets'
    | '/miaw-prix'
    | '/profile'
    | '/watch'
    | '/events-2/$id'
    | '/events-3/$id'
    | '/events/$id'
    | '/$chain/$network/$address'
    | '/events-2/$id/$predictionId'
    | '/events-3/$id/$predictionId'
    | '/events/$id/$predictionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentArenaRoute: typeof AgentArenaRoute
  BetOrMarketRoute: typeof BetOrMarketRoute
  CatwalkRoute: typeof CatwalkRoute
  ColacatRoute: typeof ColacatRoute
  DemoRoute: typeof DemoRoute
  LiveRoute: typeof LiveRoute
  MarketsRoute: typeof MarketsRoute
  MiawPrixRoute: typeof MiawPrixRoute
  ProfileRoute: typeof ProfileRoute
  WatchRoute: typeof WatchRoute
  Events2IdRoute: typeof Events2IdRouteWithChildren
  Events3IdRoute: typeof Events3IdRouteWithChildren
  EventsIdRoute: typeof EventsIdRouteWithChildren
  ChainNetworkAddressRoute: typeof ChainNetworkAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-arena': {
      id: '/agent-arena'
      path: '/agent-arena'
      fullPath: '/agent-arena'
      preLoaderRoute: typeof AgentArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-or-market': {
      id: '/bet-or-market'
      path: '/bet-or-market'
      fullPath: '/bet-or-market'
      preLoaderRoute: typeof BetOrMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catwalk': {
      id: '/catwalk'
      path: '/catwalk'
      fullPath: '/catwalk'
      preLoaderRoute: typeof CatwalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colacat': {
      id: '/colacat'
      path: '/colacat'
      fullPath: '/colacat'
      preLoaderRoute: typeof ColacatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miaw-prix': {
      id: '/miaw-prix'
      path: '/miaw-prix'
      fullPath: '/miaw-prix'
      preLoaderRoute: typeof MiawPrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-2/$id': {
      id: '/events-2/$id'
      path: '/events-2/$id'
      fullPath: '/events-2/$id'
      preLoaderRoute: typeof Events2IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-3/$id': {
      id: '/events-3/$id'
      path: '/events-3/$id'
      fullPath: '/events-3/$id'
      preLoaderRoute: typeof Events3IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$chain/$network/$address': {
      id: '/$chain/$network/$address'
      path: '/$chain/$network/$address'
      fullPath: '/$chain/$network/$address'
      preLoaderRoute: typeof ChainNetworkAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-2/$id/$predictionId': {
      id: '/events-2/$id/$predictionId'
      path: '/$predictionId'
      fullPath: '/events-2/$id/$predictionId'
      preLoaderRoute: typeof Events2IdPredictionIdRouteImport
      parentRoute: typeof Events2IdRoute
    }
    '/events-3/$id/$predictionId': {
      id: '/events-3/$id/$predictionId'
      path: '/$predictionId'
      fullPath: '/events-3/$id/$predictionId'
      preLoaderRoute: typeof Events3IdPredictionIdRouteImport
      parentRoute: typeof Events3IdRoute
    }
    '/events/$id/$predictionId': {
      id: '/events/$id/$predictionId'
      path: '/$predictionId'
      fullPath: '/events/$id/$predictionId'
      preLoaderRoute: typeof EventsIdPredictionIdRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface Events2IdRouteChildren {
  Events2IdPredictionIdRoute: typeof Events2IdPredictionIdRoute
}

const Events2IdRouteChildren: Events2IdRouteChildren = {
  Events2IdPredictionIdRoute: Events2IdPredictionIdRoute,
}

const Events2IdRouteWithChildren = Events2IdRoute._addFileChildren(
  Events2IdRouteChildren,
)

interface Events3IdRouteChildren {
  Events3IdPredictionIdRoute: typeof Events3IdPredictionIdRoute
}

const Events3IdRouteChildren: Events3IdRouteChildren = {
  Events3IdPredictionIdRoute: Events3IdPredictionIdRoute,
}

const Events3IdRouteWithChildren = Events3IdRoute._addFileChildren(
  Events3IdRouteChildren,
)

interface EventsIdRouteChildren {
  EventsIdPredictionIdRoute: typeof EventsIdPredictionIdRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdPredictionIdRoute: EventsIdPredictionIdRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentArenaRoute: AgentArenaRoute,
  BetOrMarketRoute: BetOrMarketRoute,
  CatwalkRoute: CatwalkRoute,
  ColacatRoute: ColacatRoute,
  DemoRoute: DemoRoute,
  LiveRoute: LiveRoute,
  MarketsRoute: MarketsRoute,
  MiawPrixRoute: MiawPrixRoute,
  ProfileRoute: ProfileRoute,
  WatchRoute: WatchRoute,
  Events2IdRoute: Events2IdRouteWithChildren,
  Events3IdRoute: Events3IdRouteWithChildren,
  EventsIdRoute: EventsIdRouteWithChildren,
  ChainNetworkAddressRoute: ChainNetworkAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
